[2024-01-28T13:41:58.129+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: fetch_stackoverflow_data.transform_stackoverflow_data scheduled__2023-01-10T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
