[2024-01-28T12:26:00.820+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: fetch_stackoverflow_data.load_data_to_aws_s3 scheduled__2023-01-02T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
