[2024-01-23T17:28:35.420+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: our_first_dag.greet scheduled__2023-12-15T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
